import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import NextTopLoader from 'nextjs-toploader';

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";
import { QueryProvider } from "@/providers/query-provider";
import { ModalProvider } from "@/providers/modal-provider";
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "Basic Education Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            disableTransitionOnChange
        >
          <QueryProvider>
            {children}
            <Toaster />
            <ModalProvider />
            <NextTopLoader showSpinner={false} />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
